spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/OrderCatalog
    username: postgres
    password:
    
  jpa:
    hiberate: 
      ddl-auto: none
bsl:
  customer:
    service:
      url: http://localhost:8080/v1/customer-info/customer/
   
